# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VapiCli < Formula
  desc "Voice AI for developers - Vapi CLI"
  homepage "https://vapi.ai"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/VapiAI/cli/releases/download/v0.1.2/cli_Darwin_x86_64.tar.gz"
      sha256 "75fc00711dc2b660a5c79f26bee6a8d024e8104b35632c342fa18e94631eabb0"

      def install
        bin.install "vapi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/VapiAI/cli/releases/download/v0.1.2/cli_Darwin_arm64.tar.gz"
      sha256 "9ca7ad9b10c1c25f94751baae3fd36ae68b357472ddbe80bc29fb218bcc55ab6"

      def install
        bin.install "vapi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/VapiAI/cli/releases/download/v0.1.2/cli_Linux_x86_64.tar.gz"
      sha256 "8e0f5bd7836d8b423f6efa2c55d53ba9bbfa898c52921dd2860c3222202cc614"
      def install
        bin.install "vapi"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/VapiAI/cli/releases/download/v0.1.2/cli_Linux_armv6.tar.gz"
      sha256 "23173bac66f37b9e3b750787da9601fce03cf483b516158a81b4b9e7df7806b6"
      def install
        bin.install "vapi"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/VapiAI/cli/releases/download/v0.1.2/cli_Linux_arm64.tar.gz"
      sha256 "4f3ec38509cee1158a0916135d83a63771fe1edc86acf578a2bdfebba3e9ffa2"
      def install
        bin.install "vapi"
      end
    end
  end

  test do
    system "#{bin}/vapi", "--version"
  end
end
