# This file was generated by GoReleaser. DO NOT EDIT.
cask "vapi-cli" do
  desc "Voice AI for developers - Vapi CLI"
  homepage "https://vapi.ai"
  version "0.0.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vapi-cli"

  on_macos do
    on_intel do
      url "https://github.com/VapiAI/cli/releases/download/v0.0.7/cli_Darwin_x86_64.tar.gz"
      sha256 "059d48261262f38b2342d5b95fa8e3d732ff02579f7b56b30a92f288f83ffb4c"
    end
    on_arm do
      url "https://github.com/VapiAI/cli/releases/download/v0.0.7/cli_Darwin_arm64.tar.gz"
      sha256 "263f54d3560221e9893c0d6b723900e0a391747ec5f9cdac0dfba90ce2aae67e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/VapiAI/cli/releases/download/v0.0.7/cli_Linux_x86_64.tar.gz"
      sha256 "4766fc79f962316051f16453db6218db976f31f1501b779ad64ae14cb300c956"
    end
    on_arm do
      url "https://github.com/VapiAI/cli/releases/download/v0.0.7/cli_Linux_arm64.tar.gz"
      sha256 "9f375490721469966f77e5bbb080dedecd7c511aae83f2133e27aaa2615d3137"
    end
  end

  # No zap stanza required
end
