# This file was generated by GoReleaser. DO NOT EDIT.
cask "vapi-cli" do
  desc "Voice AI for developers - Vapi CLI"
  homepage "https://vapi.ai"
  version "0.0.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vapi-cli"

  on_macos do
    on_intel do
      url "https://github.com/VapiAI/cli/releases/download/v0.0.8/cli_Darwin_x86_64.tar.gz"
      sha256 "5b56e01223129527f8b73428822ddba4e3cbd7b64fed63746355fef3638af0fc"
    end
    on_arm do
      url "https://github.com/VapiAI/cli/releases/download/v0.0.8/cli_Darwin_arm64.tar.gz"
      sha256 "d664cbe166d45e027c0d2eca4457093c97fc385e7b18ed4fbae279857c170284"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/VapiAI/cli/releases/download/v0.0.8/cli_Linux_x86_64.tar.gz"
      sha256 "989fa37d3c2d87bf7a71648dcf769053de15953587d7f85bd35d0d68afde5ef4"
    end
    on_arm do
      url "https://github.com/VapiAI/cli/releases/download/v0.0.8/cli_Linux_arm64.tar.gz"
      sha256 "1fdb938d9f956b4c0ee530344bda5873a94c34419f5754346aecd4376a9512b6"
    end
  end

  # No zap stanza required
end
