# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VapiCli < Formula
  desc "Voice AI for developers - Vapi CLI"
  homepage "https://vapi.ai"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/VapiAI/cli/releases/download/v0.0.5/cli_Darwin_x86_64.tar.gz"
      sha256 "cbef306b0ef28bbe205e4e152dd290ae7a98c7715d1d29e06627ccf323b5ce9a"

      def install
        bin.install "vapi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/VapiAI/cli/releases/download/v0.0.5/cli_Darwin_arm64.tar.gz"
      sha256 "dd97d28d62be3439cbc8c80f88b835647797aa442e19ac830de7204ae51e89b6"

      def install
        bin.install "vapi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/VapiAI/cli/releases/download/v0.0.5/cli_Linux_x86_64.tar.gz"
      sha256 "a18e21f05a52bcd376b1f61d61d7d0cf233eb08b05b3742c1a27a34a4da7aa1b"
      def install
        bin.install "vapi"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/VapiAI/cli/releases/download/v0.0.5/cli_Linux_armv6.tar.gz"
      sha256 "c20476f3dc637ac2cbb417089f32b492fac94f5d28cbdfc36c67d5d8907a18bb"
      def install
        bin.install "vapi"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/VapiAI/cli/releases/download/v0.0.5/cli_Linux_arm64.tar.gz"
      sha256 "25170651568141b469b91083fd8889bfa73d5f748219db731d56ffcfdbbc1f82"
      def install
        bin.install "vapi"
      end
    end
  end

  test do
    system "#{bin}/vapi", "--version"
  end
end
