# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VapiCli < Formula
  desc "Voice AI for developers - Vapi CLI"
  homepage "https://vapi.ai"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/VapiAI/cli/releases/download/v0.1.1/cli_Darwin_x86_64.tar.gz"
      sha256 "15de967be793c1a2bbfd5cb10893655dc235e85e4827cc2de805af335c86cc9a"

      def install
        bin.install "vapi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/VapiAI/cli/releases/download/v0.1.1/cli_Darwin_arm64.tar.gz"
      sha256 "7c9179ce4b56c3dd58281b79170fed850878ee012f8a95a74505ebe63f3ad0e2"

      def install
        bin.install "vapi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/VapiAI/cli/releases/download/v0.1.1/cli_Linux_x86_64.tar.gz"
      sha256 "b520782dc4f00be79b27a33e6732b8ba76eb775df58cc49da993ef6eba97bfe4"
      def install
        bin.install "vapi"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/VapiAI/cli/releases/download/v0.1.1/cli_Linux_armv6.tar.gz"
      sha256 "df07206b15c47d7ab69d57f9d07b8616096cb1b91d853bbab47c064e3a84b601"
      def install
        bin.install "vapi"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/VapiAI/cli/releases/download/v0.1.1/cli_Linux_arm64.tar.gz"
      sha256 "91b5c899889495589296604ef226a44901b65b4a851a73727df3f8e65c1af4f5"
      def install
        bin.install "vapi"
      end
    end
  end

  test do
    system "#{bin}/vapi", "--version"
  end
end
