# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VapiCli < Formula
  desc "Voice AI for developers - Vapi CLI"
  homepage "https://vapi.ai"
  version "0.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/VapiAI/cli/releases/download/v0.0.6/cli_Darwin_x86_64.tar.gz"
      sha256 "57591dd820cbb254e22a6d463ff4df2106a54d0f8df63b09013e2aedbe60a113"

      def install
        bin.install "vapi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/VapiAI/cli/releases/download/v0.0.6/cli_Darwin_arm64.tar.gz"
      sha256 "8f13390c2cf934d2a8f6645f0bad17f50184064d42c7c38f9bb08a34f963d95d"

      def install
        bin.install "vapi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/VapiAI/cli/releases/download/v0.0.6/cli_Linux_x86_64.tar.gz"
      sha256 "f577920bb9166237308191e42b0d2213eb8f218de9dfc70dfd8812b1bd0925fb"
      def install
        bin.install "vapi"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/VapiAI/cli/releases/download/v0.0.6/cli_Linux_armv6.tar.gz"
      sha256 "0202819d561f0acf5904a6f30237af022faf5b1c42b7f8cbf4ee7c2d723a8421"
      def install
        bin.install "vapi"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/VapiAI/cli/releases/download/v0.0.6/cli_Linux_arm64.tar.gz"
      sha256 "87886f070e6aa84075457be1a894bb13e50ae28deabaebe9b979247b2cd7d071"
      def install
        bin.install "vapi"
      end
    end
  end

  test do
    system "#{bin}/vapi", "--version"
  end
end
